# Generated by Django 2.1.1 on 2018-10-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20181007_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='armchair',
            name='image',
            field=models.ImageField(blank=True, upload_to='products_images'),
        ),
        migrations.AddField(
            model_name='kettle',
            name='image',
            field=models.ImageField(blank=True, upload_to='products_images'),
        ),
        migrations.AddField(
            model_name='lamp',
            name='image',
            field=models.ImageField(blank=True, upload_to='products_images'),
        ),
        migrations.AddField(
            model_name='table',
            name='image',
            field=models.ImageField(blank=True, upload_to='products_images'),
        ),
    ]
