# Generated by Django 2.1.1 on 2018-10-18 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20181014_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='armchair',
            name='Manufacturer',
        ),
        migrations.RemoveField(
            model_name='armchair',
            name='image',
        ),
        migrations.RemoveField(
            model_name='kettle',
            name='Manufacturer',
        ),
        migrations.RemoveField(
            model_name='kettle',
            name='image',
        ),
        migrations.RemoveField(
            model_name='lamp',
            name='Manufacturer',
        ),
        migrations.RemoveField(
            model_name='lamp',
            name='image',
        ),
        migrations.RemoveField(
            model_name='table',
            name='Manufacturer',
        ),
        migrations.RemoveField(
            model_name='table',
            name='image',
        ),
        migrations.DeleteModel(
            name='Armchair',
        ),
        migrations.DeleteModel(
            name='Kettle',
        ),
        migrations.DeleteModel(
            name='Lamp',
        ),
        migrations.DeleteModel(
            name='Table',
        ),
    ]
